# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4a933c5484065237b3088e80c92efb56ceee291fd92bc46de196d162d61f376dc8274d56108731c7f03325fc099d44488785ec97a9c2094b2bdc62c740acfa6

test:
  secret_key_base: 257e12866dc0faeb09f083a4dda77d6a49c2a11be518ee3e8f58e9ced5876fd7f0770efaa1ad748d22bf978723004fb8c02ef4b427187afe1a9c65b88938a276

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
